### ISSUE TITLE
independent program for windows

### ISSUE THREAD

**Issue by codename4748** [RoboPhred/oni-duplicity#42] opened 2018-10-16 05:59 UTC
are you planning on making it an independent program like stardew valley save editor? that would be cool

**Comment by RoboPhred** [comment] 2019-02-28 01:13
Mostly I am spending my time trying to add new features, but I could possibly see about using Electron to create a standalone version.

**Comment by RoboPhred** [comment] 2019-02-28 01:17
Duplicate of https://github.com/RoboPhred/oni-duplicity/issues/25

**Closed as completed by RoboPhred** 2019-02-28 01:17 UTC
