### ISSUE TITLE
Error loading save

### ISSUE THREAD

**Issue by GamezUzer** [RoboPhred/oni-duplicity#62] opened 2019-08-06 15:48 UTC
Error while processing content: Identifier "<ReceiveChannel>k__BackingField" has invalid characters. This most likely indicates a parser error or change in serializer standards.
![Supernova](https://user-images.githubusercontent.com/53830229/62555225-f3443380-b848-11e9-8b8f-30dc49a5c238.png)

edit: savegame

**Comment by RoboPhred** [comment] 2019-08-18 18:30
Can you upload the save file that is causing this?

**Comment by GamezUzer** [comment] 2019-08-20 13:45
i no have this save more, sorry, but, provable cause is any DEAD dupe, dead
but not buried, or was deleted by accident with deletion tool, no longer
sure.

Em dom, 18 de ago de 2019 às 15:30, RoboPhred <notifications@github.com>
escreveu:

**Comment by operinko** [comment] 2019-08-22 15:09
I'm having the same issue with a rather heavy list of mods.
So in my case, it could be caused by one of those.
[The Subterranean Spacecamp.zip](https://github.com/RoboPhred/oni-duplicity/files/3530749/The.Subterranean.Spacecamp.zip)

**Comment by RoboPhred** [comment] 2019-08-31 18:24
Fixed in 3.8.4

**Closed as completed by RoboPhred** 2019-08-31 18:24 UTC
