### ISSUE TITLE
Assign traits to all duplicants at once #featureRequest

### ISSUE THREAD

**Issue by jessehattabaugh** [RoboPhred/oni-duplicity#36] opened 2018-08-19 18:56 UTC
Would be nice to have when I'm trying to make sure none of my dupes are Destructive. Currently have to go into each Dupe and check the boxes.

**Comment by RoboPhred** [comment] 2019-02-28 01:17
~~Duplicate of https://github.com/RoboPhred/oni-duplicity/issues/36~~

Scratch that, linked issue was attributes.

**Comment by RoboPhred** [comment] 2019-11-16 15:40
This is implemented by being able to copy and paste attributes between duplicants

**Closed as completed by RoboPhred** 2019-11-16 15:40 UTC
Labels: enhancement
